@NexusMonitor.Api_HostAddress = http://localhost:5210

GET {{NexusMonitor.Api_HostAddress}}/api/device/
Accept: application/json

### GET, argument jako liczba (int), 

GET {{NexusMonitor.Api_HostAddress}}/api/device/2
Accept: application/json

### GET, argument jako tekst 

GET {{NexusMonitor.Api_HostAddress}}/api/device?DeviceName=Nowe3
Accept: application/json


### Dodaj (POST)
POST {{NexusMonitor.Api_HostAddress}}/api/device
Content-Type: application/json
{
  "DeviceName": "ter",
  "HighThreshold": 123.12,
  "DeviceType":"asd"
}

### Zaktualizuj (PUT)
PUT {{NexusMonitor.Api_HostAddress}}/api/device/2
Content-Type: application/json
{
  "DeviceName": "TestMapping",
  "HighThreshold": 123.12,
  "DeviceType":"asd"
}

### Usuñ (DELETE)
DELETE {{NexusMonitor.Api_HostAddress}}/api/device/1


### Test Error Throw
GET {{NexusMonitor.Api_HostAddress}}/api/device/server-error/