@NexusMonitor.Api_HostAddress = http://localhost:5210

GET {{NexusMonitor.Api_HostAddress}}/api/device/
Accept: application/json

### GET, argument jako liczba (int), 

GET {{NexusMonitor.Api_HostAddress}}/api/device/1
Accept: application/json

### GET, argument jako tekst 

GET {{NexusMonitor.Api_HostAddress}}/api/device?DeviceName=Device%202
Accept: application/json


### Dodaj (POST)
POST {{NexusMonitor.Api_HostAddress}}/api/device
Content-Type: application/json
{
  "DeviceName": "Nowe"
}

### Zaktualizuj (PUT)
PUT {{NexusMonitor.Api_HostAddress}}/api/device/1
Content-Type: application/json
{
  "DeviceName": "Name zmienione"
}

### Usuñ (DELETE)
DELETE {{NexusMonitor.Api_HostAddress}}/api/device/1
