@NexusMonitor.Api_HostAddress = http://localhost:5210

GET {{NexusMonitor.Api_HostAddress}}/api/device/
Accept: application/json

### GET, argument jako liczba (int), 

GET {{NexusMonitor.Api_HostAddress}}/api/device/3004
Accept: application/json

### GET, argument jako tekst 

GET {{NexusMonitor.Api_HostAddress}}/api/device?DeviceName=Nowe3
Accept: application/json


### Dodaj (POST)
POST {{NexusMonitor.Api_HostAddress}}/api/device
Content-Type: application/json
{
  "DeviceName": "Test walidators z record DTO"
}

### Zaktualizuj (PUT)
PUT {{NexusMonitor.Api_HostAddress}}/api/device/3004
Content-Type: application/json
{
  "DeviceName": "Record DTO",
  "HighThreshold": 123.12,
  "DeviceType":"Mircowave",
  "MeasurementsUnit":"km/h"
}

### Usuñ (DELETE)
DELETE {{NexusMonitor.Api_HostAddress}}/api/device/3003


### Test Error Throw
GET {{NexusMonitor.Api_HostAddress}}/api/device/server-error/